FROM node:11

COPY package.json /home/node/app/
COPY yarn.lock /home/node/app/

WORKDIR /home/node/app

RUN yarn install

COPY tslint.json .
COPY vue.config.js .
COPY tsconfig.json .
COPY babel.config.js .

CMD yarn run serve --host 0.0.0.0
