FROM python:3.7.2
RUN apt-get update && apt-get install -y build-essential python-dev
COPY requirements-normal.txt /code/
WORKDIR /code
RUN pip install wheel && pip install -r requirements-normal.txt

ENV PYTHONPATH /code

CMD python manage.py runserver 0.0.0.0:8000